seed: 42
format: gen9doublesou
total_timesteps: 5000000
rollout_workers: 8
batch_size: 32768
update_epochs: 4
gamma: 0.997
gae_lambda: 0.95
clip_ratio: 0.2
entropy_coef: 0.01
vf_coef: 0.5
learning_rate: 3.0e-4
max_grad_norm: 0.5
lstm_hidden: 64
mixed_precision: true
